module.exports = {
	required: [
		'BACKEND_SPREADSHEET',
		'DONATION_SPREADSHEET',
		'GOOGLE_PROJECT_CREDENTIALS',
		'MAILCHIMP_KEY',
		'PORTAL_PATH',
		'PORTAL_UUID',
		'RAISELY_WEBHOOK_KEY',
		'RAISELY_TOKEN',
		'VIP_DONOR_THRESHOLD_CENTS',
		'WEBSITE_PATH',
	],
	optional: [
	],
};
