name: Raisely Custom Components

on:
    push:
        paths:
            - 'cc-raisely-components/**'
            - '.github/workflows/components-ci.yml'

jobs:
    deploy:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 14

            - name: Cache node modules
              uses: actions/cache@v2
              env:
                  cache-name: cache-node-modules-components
              with:
                  # npm cache files are stored in `~/.npm` on Linux/macOS
                  path: ~/.npm
                  key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('cc-raisely-components/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-build-${{ env.cache-name }}-
                      ${{ runner.os }}-build-
                      ${{ runner.os }}-

            - name: Install Dependencies
              working-directory: ./cc-raisely-components
              run: npm ci

            - name: Test
              working-directory: ./cc-raisely-components
              run: npm test

            - name: Set Production environment
              if: github.ref == 'refs/heads/main'
              working-directory: ./api
              run: |
                  echo "RAISELY_TOKEN=${RAISELY_TOKEN}" >> $GITHUB_ENV
              env:
                  GCLOUD_AUTH: ${{ secrets.RAISELY_PRODUCTION_TOKEN }}

            - name: Set Staging environment
              if: github.ref != 'refs/heads/main'
              working-directory: ./api
              run: |
                  echo "Hi!";
            #       echo $GITHUB_ENV
            #       echo "RAISELY_TOKEN=${RAISELY_TOKEN}" >> $GITHUB_ENV
            #   env:
            #       GCLOUD_AUTH: ${{ secrets.RAISELY_STAGING_TOKEN }}

            # - name: Deploy components
            #   working-directory: ./cc-raisely-components
            #   run: |
            #       npm run deploy
